# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4688265e61103e4758d09c04908571252e026c38d7eeb3493a746656fa9351b2e060508d0a28b21c34d4c48e1a43398a4959c6ed72b4b429bb74e037ea5b0d7d

test:
  secret_key_base: 6daccc3538c60d384cdc6cd859a558affce3bddd3a62afaadfd80f54a0cd5dd616494a6e6859cba29d5a7a54d6bf3399f9be3300e958f701d22f2a7baf42bbf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
